baseURL = "https://johannesprinz.com/"
languageCode = "en-us"
title = "Johannes Prinz"

theme = "m10c"
[params]
  author = "Johannes Prinz"
  description = "In persuit of Truth | Health | Wealth"
  # avatar = "https://en.gravatar.com/userimage/67495667/ced769184eb23a69f0e989da03afd923.jpg?size=200"
  avatar = "https://avatars.githubusercontent.com/u/1687127"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/johannesprinz"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/pr1nzj"