baseURL = "/" # "https://www.johannesprinz.com/"
languageCode = "en-us"
title = "Johannes Prinz"
theme = "m10c"
paginate = 10

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    pre = "<i class='fa fa-blog'></i>"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    pre = "<i class='fa fa-tags'></i>"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    pre = "<i class='fa fa-books'></i>"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    pre = "<i class='fa fa-heart'></i>"
    url = "/about/"
    weight = 4

[params]
  author = "Johannes Prinz"
  description = "My thoughts unravelling"
  avatar = "https://avatars.githubusercontent.com/u/1687127"
  menu_item_separator = " | " # " </br> "
  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/johannesprinz"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/johannesprinz"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/pr1nzj"
  [[params.social]]
    icon = "youtube"
    name = "YouTube"
    url = "https://youtube.com/playlist?list=PLbB0DkO_4qsTM3LAO-1d7lkvY2PtRyEpQ"
  # [menu]
  # [[menu.main]]
  #   identifier = "about"
  #   name = "About"
  #   pre = "<i class='fa fa-heart'></i>"
  #   url = "https://johannesprinz.com"
  #   weight = -110
  # [[menu.main]]
  #   name = "Getting Started"
  #   post = "<span class='alert'>New!</span>"
  #   pre = "<i class='fa fa-road'></i>"
  #   url = "/getting-started/"
  #   weight = -100
